export const SUPPLIERS = {
  NSB: { code: "NSB", name: "Nussbaum" },
  ST: { code: "ST", name: "Sanitas Troesch" },
  GM: { code: "GM", name: "Getaz Miauton" },
  GEB: { code: "GEB", name: "Geberit" },
};

export const MOCK_CATALOGUE = [
  {
    "id": "nsb-1",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9953-12",
    "name": "Tuyau acier inox 1.4521 Optipress ï¿½ 12 mm",
    "category": "tuyau_inox",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "m",
    "base_price": 15.21
  },
  {
    "id": "nsb-2",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6673-15",
    "name": "Tuyau acier inox 1.4521 Optipress ï¿½ 15 mm",
    "category": "tuyau_inox",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "m",
    "base_price": 31.00
  },
  {
    "id": "nsb-3",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1717-18",
    "name": "Tuyau acier inox 1.4521 Optipress ï¿½ 18 mm",
    "category": "tuyau_inox",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "m",
    "base_price": 29.26
  },
  {
    "id": "nsb-4",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1129-22",
    "name": "Tuyau acier inox 1.4521 Optipress ï¿½ 22 mm",
    "category": "tuyau_inox",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "m",
    "base_price": 25.77
  },
  {
    "id": "nsb-5",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2051-28",
    "name": "Tuyau acier inox 1.4521 Optipress ï¿½ 28 mm",
    "category": "tuyau_inox",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "m",
    "base_price": 26.00
  },
  {
    "id": "nsb-6",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4473-35",
    "name": "Tuyau acier inox 1.4521 Optipress ï¿½ 35 mm",
    "category": "tuyau_inox",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "m",
    "base_price": 31.55
  },
  {
    "id": "nsb-7",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1214-42",
    "name": "Tuyau acier inox 1.4521 Optipress ï¿½ 42 mm",
    "category": "tuyau_inox",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "m",
    "base_price": 11.75
  },
  {
    "id": "nsb-8",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2103-54",
    "name": "Tuyau acier inox 1.4521 Optipress ï¿½ 54 mm",
    "category": "tuyau_inox",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "m",
    "base_price": 11.99
  },
  {
    "id": "nsb-9",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8567-12",
    "name": "Coude 90ï¿½ ï¿½ sertir inox ï¿½ 12 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.78
  },
  {
    "id": "nsb-10",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2056-15",
    "name": "Coude 90ï¿½ ï¿½ sertir inox ï¿½ 15 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.47
  },
  {
    "id": "nsb-11",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9614-18",
    "name": "Coude 90ï¿½ ï¿½ sertir inox ï¿½ 18 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.93
  },
  {
    "id": "nsb-12",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6566-22",
    "name": "Coude 90ï¿½ ï¿½ sertir inox ï¿½ 22 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 22.37
  },
  {
    "id": "nsb-13",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8101-28",
    "name": "Coude 90ï¿½ ï¿½ sertir inox ï¿½ 28 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 33.64
  },
  {
    "id": "nsb-14",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7514-35",
    "name": "Coude 90ï¿½ ï¿½ sertir inox ï¿½ 35 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 26.89
  },
  {
    "id": "nsb-15",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2545-42",
    "name": "Coude 90ï¿½ ï¿½ sertir inox ï¿½ 42 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 25.32
  },
  {
    "id": "nsb-16",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2766-54",
    "name": "Coude 90ï¿½ ï¿½ sertir inox ï¿½ 54 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.75
  },
  {
    "id": "nsb-17",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8014-12",
    "name": "Coude 45ï¿½ ï¿½ sertir inox ï¿½ 12 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 34.15
  },
  {
    "id": "nsb-18",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7954-15",
    "name": "Coude 45ï¿½ ï¿½ sertir inox ï¿½ 15 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.03
  },
  {
    "id": "nsb-19",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6669-18",
    "name": "Coude 45ï¿½ ï¿½ sertir inox ï¿½ 18 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.43
  },
  {
    "id": "nsb-20",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-3443-22",
    "name": "Coude 45ï¿½ ï¿½ sertir inox ï¿½ 22 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.21
  },
  {
    "id": "nsb-21",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6704-28",
    "name": "Coude 45ï¿½ ï¿½ sertir inox ï¿½ 28 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 27.56
  },
  {
    "id": "nsb-22",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1936-35",
    "name": "Coude 45ï¿½ ï¿½ sertir inox ï¿½ 35 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.40
  },
  {
    "id": "nsb-23",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5440-42",
    "name": "Coude 45ï¿½ ï¿½ sertir inox ï¿½ 42 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.28
  },
  {
    "id": "nsb-24",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4045-54",
    "name": "Coude 45ï¿½ ï¿½ sertir inox ï¿½ 54 mm",
    "category": "coude_sertir",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.93
  },
  {
    "id": "nsb-25",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7462-12",
    "name": "Manchon ï¿½ sertir inox ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.03
  },
  {
    "id": "nsb-26",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8174-15",
    "name": "Manchon ï¿½ sertir inox ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 20.28
  },
  {
    "id": "nsb-27",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9483-18",
    "name": "Manchon ï¿½ sertir inox ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.76
  },
  {
    "id": "nsb-28",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2981-22",
    "name": "Manchon ï¿½ sertir inox ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.64
  },
  {
    "id": "nsb-29",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8787-28",
    "name": "Manchon ï¿½ sertir inox ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.13
  },
  {
    "id": "nsb-30",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2168-35",
    "name": "Manchon ï¿½ sertir inox ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.71
  },
  {
    "id": "nsb-31",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8482-42",
    "name": "Manchon ï¿½ sertir inox ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 12.90
  },
  {
    "id": "nsb-32",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2905-54",
    "name": "Manchon ï¿½ sertir inox ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.82
  },
  {
    "id": "nsb-33",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6413-12",
    "name": "Manchon de rï¿½duction inox ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.13
  },
  {
    "id": "nsb-34",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8565-15",
    "name": "Manchon de rï¿½duction inox ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 20.83
  },
  {
    "id": "nsb-35",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9963-18",
    "name": "Manchon de rï¿½duction inox ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 10.69
  },
  {
    "id": "nsb-36",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1341-22",
    "name": "Manchon de rï¿½duction inox ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 30.37
  },
  {
    "id": "nsb-37",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9579-28",
    "name": "Manchon de rï¿½duction inox ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 31.29
  },
  {
    "id": "nsb-38",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8404-35",
    "name": "Manchon de rï¿½duction inox ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 24.49
  },
  {
    "id": "nsb-39",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9491-42",
    "name": "Manchon de rï¿½duction inox ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 34.40
  },
  {
    "id": "nsb-40",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5767-54",
    "name": "Manchon de rï¿½duction inox ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 32.93
  },
  {
    "id": "nsb-41",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4962-12",
    "name": "Tï¿½ ï¿½ sertir inox ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.34
  },
  {
    "id": "nsb-42",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2162-15",
    "name": "Tï¿½ ï¿½ sertir inox ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 28.60
  },
  {
    "id": "nsb-43",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2837-18",
    "name": "Tï¿½ ï¿½ sertir inox ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 12.14
  },
  {
    "id": "nsb-44",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5497-22",
    "name": "Tï¿½ ï¿½ sertir inox ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 30.23
  },
  {
    "id": "nsb-45",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4535-28",
    "name": "Tï¿½ ï¿½ sertir inox ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 30.67
  },
  {
    "id": "nsb-46",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7465-35",
    "name": "Tï¿½ ï¿½ sertir inox ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.73
  },
  {
    "id": "nsb-47",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7658-42",
    "name": "Tï¿½ ï¿½ sertir inox ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 27.76
  },
  {
    "id": "nsb-48",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9708-54",
    "name": "Tï¿½ ï¿½ sertir inox ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.89
  },
  {
    "id": "nsb-49",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4873-12",
    "name": "Collier de fixation isophonique ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 31.38
  },
  {
    "id": "nsb-50",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2295-15",
    "name": "Collier de fixation isophonique ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.26
  },
  {
    "id": "nsb-51",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6783-18",
    "name": "Collier de fixation isophonique ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.85
  },
  {
    "id": "nsb-52",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6189-22",
    "name": "Collier de fixation isophonique ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 32.37
  },
  {
    "id": "nsb-53",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5180-28",
    "name": "Collier de fixation isophonique ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 9.61
  },
  {
    "id": "nsb-54",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4289-35",
    "name": "Collier de fixation isophonique ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 27.46
  },
  {
    "id": "nsb-55",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9433-42",
    "name": "Collier de fixation isophonique ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.67
  },
  {
    "id": "nsb-56",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7673-54",
    "name": "Collier de fixation isophonique ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.91
  },
  {
    "id": "nsb-57",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8847-12",
    "name": "Coquille isolante en PIR avec gaine PVC ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "m",
    "base_price": 21.49
  },
  {
    "id": "nsb-58",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5795-15",
    "name": "Coquille isolante en PIR avec gaine PVC ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "m",
    "base_price": 27.31
  },
  {
    "id": "nsb-59",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9244-18",
    "name": "Coquille isolante en PIR avec gaine PVC ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "m",
    "base_price": 14.73
  },
  {
    "id": "nsb-60",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1929-22",
    "name": "Coquille isolante en PIR avec gaine PVC ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "m",
    "base_price": 32.22
  },
  {
    "id": "nsb-61",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1965-28",
    "name": "Coquille isolante en PIR avec gaine PVC ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "m",
    "base_price": 6.73
  },
  {
    "id": "nsb-62",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-3073-35",
    "name": "Coquille isolante en PIR avec gaine PVC ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "m",
    "base_price": 16.70
  },
  {
    "id": "nsb-63",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6802-42",
    "name": "Coquille isolante en PIR avec gaine PVC ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "m",
    "base_price": 31.05
  },
  {
    "id": "nsb-64",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7676-54",
    "name": "Coquille isolante en PIR avec gaine PVC ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "m",
    "base_price": 12.37
  },
  {
    "id": "st-65",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.774268",
    "name": "Tube cuivre en barre ï¿½croui ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "m",
    "base_price": 9.61
  },
  {
    "id": "st-66",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.862942",
    "name": "Tube cuivre en barre ï¿½croui ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "m",
    "base_price": 21.68
  },
  {
    "id": "st-67",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.595027",
    "name": "Tube cuivre en barre ï¿½croui ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "m",
    "base_price": 12.98
  },
  {
    "id": "st-68",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.216366",
    "name": "Tube cuivre en barre ï¿½croui ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "m",
    "base_price": 12.01
  },
  {
    "id": "st-69",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.832567",
    "name": "Tube cuivre en barre ï¿½croui ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "m",
    "base_price": 4.16
  },
  {
    "id": "st-70",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.492687",
    "name": "Tube cuivre en barre ï¿½croui ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "m",
    "base_price": 6.37
  },
  {
    "id": "st-71",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.793748",
    "name": "Tube cuivre en barre ï¿½croui ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "m",
    "base_price": 4.18
  },
  {
    "id": "st-72",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.888565",
    "name": "Tube cuivre en barre ï¿½croui ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "m",
    "base_price": 19.53
  },
  {
    "id": "st-73",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.292644",
    "name": "Coude 90ï¿½ cuivre ï¿½ souder ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.46
  },
  {
    "id": "st-74",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.247341",
    "name": "Coude 90ï¿½ cuivre ï¿½ souder ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.51
  },
  {
    "id": "st-75",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.658747",
    "name": "Coude 90ï¿½ cuivre ï¿½ souder ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 9.55
  },
  {
    "id": "st-76",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.661115",
    "name": "Coude 90ï¿½ cuivre ï¿½ souder ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.85
  },
  {
    "id": "st-77",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.269587",
    "name": "Coude 90ï¿½ cuivre ï¿½ souder ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 4.41
  },
  {
    "id": "st-78",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.768324",
    "name": "Coude 90ï¿½ cuivre ï¿½ souder ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.18
  },
  {
    "id": "st-79",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.720430",
    "name": "Coude 90ï¿½ cuivre ï¿½ souder ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.62
  },
  {
    "id": "st-80",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.657790",
    "name": "Coude 90ï¿½ cuivre ï¿½ souder ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.38
  },
  {
    "id": "st-81",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.403630",
    "name": "Manchon cuivre ï¿½ souder ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.91
  },
  {
    "id": "st-82",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.537552",
    "name": "Manchon cuivre ï¿½ souder ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.85
  },
  {
    "id": "st-83",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.813184",
    "name": "Manchon cuivre ï¿½ souder ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.50
  },
  {
    "id": "st-84",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.800416",
    "name": "Manchon cuivre ï¿½ souder ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.28
  },
  {
    "id": "st-85",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.611123",
    "name": "Manchon cuivre ï¿½ souder ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.18
  },
  {
    "id": "st-86",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.319725",
    "name": "Manchon cuivre ï¿½ souder ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.70
  },
  {
    "id": "st-87",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.293216",
    "name": "Manchon cuivre ï¿½ souder ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.80
  },
  {
    "id": "st-88",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.159206",
    "name": "Manchon cuivre ï¿½ souder ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.07
  },
  {
    "id": "st-89",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.188006",
    "name": "Raccord de transition bronze/cuivre ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.33
  },
  {
    "id": "st-90",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.795067",
    "name": "Raccord de transition bronze/cuivre ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.16
  },
  {
    "id": "st-91",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.693789",
    "name": "Raccord de transition bronze/cuivre ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.67
  },
  {
    "id": "st-92",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.358525",
    "name": "Raccord de transition bronze/cuivre ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.10
  },
  {
    "id": "st-93",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.853403",
    "name": "Raccord de transition bronze/cuivre ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.11
  },
  {
    "id": "st-94",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.883994",
    "name": "Raccord de transition bronze/cuivre ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.18
  },
  {
    "id": "st-95",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.998149",
    "name": "Raccord de transition bronze/cuivre ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 12.61
  },
  {
    "id": "st-96",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.237165",
    "name": "Raccord de transition bronze/cuivre ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.45
  },
  {
    "id": "st-97",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.871566",
    "name": "Tï¿½ cuivre ï¿½ souder ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.85
  },
  {
    "id": "st-98",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.706000",
    "name": "Tï¿½ cuivre ï¿½ souder ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.95
  },
  {
    "id": "st-99",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.428725",
    "name": "Tï¿½ cuivre ï¿½ souder ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.68
  },
  {
    "id": "st-100",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.681738",
    "name": "Tï¿½ cuivre ï¿½ souder ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.38
  },
  {
    "id": "st-101",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.562362",
    "name": "Tï¿½ cuivre ï¿½ souder ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.74
  },
  {
    "id": "st-102",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.190465",
    "name": "Tï¿½ cuivre ï¿½ souder ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.91
  },
  {
    "id": "st-103",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.546036",
    "name": "Tï¿½ cuivre ï¿½ souder ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.48
  },
  {
    "id": "st-104",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.492368",
    "name": "Tï¿½ cuivre ï¿½ souder ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.77
  },
  {
    "id": "st-105",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.813631",
    "name": "Vanne ï¿½ bille laiton ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.10
  },
  {
    "id": "st-106",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.239486",
    "name": "Vanne ï¿½ bille laiton ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.14
  },
  {
    "id": "st-107",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.527774",
    "name": "Vanne ï¿½ bille laiton ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 9.10
  },
  {
    "id": "st-108",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.957037",
    "name": "Vanne ï¿½ bille laiton ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.44
  },
  {
    "id": "st-109",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.957714",
    "name": "Vanne ï¿½ bille laiton ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.36
  },
  {
    "id": "st-110",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.727018",
    "name": "Vanne ï¿½ bille laiton ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.00
  },
  {
    "id": "st-111",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.510044",
    "name": "Vanne ï¿½ bille laiton ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.79
  },
  {
    "id": "st-112",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.716503",
    "name": "Vanne ï¿½ bille laiton ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.83
  },
  {
    "id": "st-113",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.616711",
    "name": "Collier simple M8 ï¿½ 12 mm",
    "category": "autre",
    "specification": "ï¿½ 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.50
  },
  {
    "id": "st-114",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.601923",
    "name": "Collier simple M8 ï¿½ 15 mm",
    "category": "autre",
    "specification": "ï¿½ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.04
  },
  {
    "id": "st-115",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.278473",
    "name": "Collier simple M8 ï¿½ 18 mm",
    "category": "autre",
    "specification": "ï¿½ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.41
  },
  {
    "id": "st-116",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.538613",
    "name": "Collier simple M8 ï¿½ 22 mm",
    "category": "autre",
    "specification": "ï¿½ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.23
  },
  {
    "id": "st-117",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.737057",
    "name": "Collier simple M8 ï¿½ 28 mm",
    "category": "autre",
    "specification": "ï¿½ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.97
  },
  {
    "id": "st-118",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.204215",
    "name": "Collier simple M8 ï¿½ 35 mm",
    "category": "autre",
    "specification": "ï¿½ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 20.95
  },
  {
    "id": "st-119",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.688098",
    "name": "Collier simple M8 ï¿½ 42 mm",
    "category": "autre",
    "specification": "ï¿½ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.93
  },
  {
    "id": "st-120",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.136669",
    "name": "Collier simple M8 ï¿½ 54 mm",
    "category": "autre",
    "specification": "ï¿½ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.63
  },
  {
    "id": "gm-121",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/85/1775",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc ï¿½ 16 mm",
    "category": "autre",
    "specification": "ï¿½ 16 mm",
    "active": true,
    "unit": "m",
    "base_price": 5.10
  },
  {
    "id": "gm-122",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/39/1766",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc ï¿½ 20 mm",
    "category": "autre",
    "specification": "ï¿½ 20 mm",
    "active": true,
    "unit": "m",
    "base_price": 5.01
  },
  {
    "id": "gm-123",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/43/1541",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc ï¿½ 26 mm",
    "category": "autre",
    "specification": "ï¿½ 26 mm",
    "active": true,
    "unit": "m",
    "base_price": 15.99
  },
  {
    "id": "gm-124",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/49/1204",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc ï¿½ 32 mm",
    "category": "autre",
    "specification": "ï¿½ 32 mm",
    "active": true,
    "unit": "m",
    "base_price": 13.35
  },
  {
    "id": "gm-125",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/87/7440",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc ï¿½ 40 mm",
    "category": "autre",
    "specification": "ï¿½ 40 mm",
    "active": true,
    "unit": "m",
    "base_price": 3.64
  },
  {
    "id": "gm-126",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/73/6051",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc ï¿½ 50 mm",
    "category": "autre",
    "specification": "ï¿½ 50 mm",
    "active": true,
    "unit": "m",
    "base_price": 5.48
  },
  {
    "id": "gm-127",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/76/4759",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc ï¿½ 63 mm",
    "category": "autre",
    "specification": "ï¿½ 63 mm",
    "active": true,
    "unit": "m",
    "base_price": 10.77
  },
  {
    "id": "gm-128",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/60/2144",
    "name": "Coude 90ï¿½ ï¿½ sertir multicouche ï¿½ 16 mm",
    "category": "autre",
    "specification": "ï¿½ 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.62
  },
  {
    "id": "gm-129",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/49/6802",
    "name": "Coude 90ï¿½ ï¿½ sertir multicouche ï¿½ 20 mm",
    "category": "autre",
    "specification": "ï¿½ 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.11
  },
  {
    "id": "gm-130",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/74/3096",
    "name": "Coude 90ï¿½ ï¿½ sertir multicouche ï¿½ 26 mm",
    "category": "autre",
    "specification": "ï¿½ 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.12
  },
  {
    "id": "gm-131",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/10/8311",
    "name": "Coude 90ï¿½ ï¿½ sertir multicouche ï¿½ 32 mm",
    "category": "autre",
    "specification": "ï¿½ 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.60
  },
  {
    "id": "gm-132",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/67/1966",
    "name": "Coude 90ï¿½ ï¿½ sertir multicouche ï¿½ 40 mm",
    "category": "autre",
    "specification": "ï¿½ 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.71
  },
  {
    "id": "gm-133",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/98/8905",
    "name": "Coude 90ï¿½ ï¿½ sertir multicouche ï¿½ 50 mm",
    "category": "autre",
    "specification": "ï¿½ 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.07
  },
  {
    "id": "gm-134",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/99/7401",
    "name": "Coude 90ï¿½ ï¿½ sertir multicouche ï¿½ 63 mm",
    "category": "autre",
    "specification": "ï¿½ 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.46
  },
  {
    "id": "gm-135",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/97/6922",
    "name": "Tï¿½ ï¿½gal ï¿½ sertir multicouche ï¿½ 16 mm",
    "category": "autre",
    "specification": "ï¿½ 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.86
  },
  {
    "id": "gm-136",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/67/4019",
    "name": "Tï¿½ ï¿½gal ï¿½ sertir multicouche ï¿½ 20 mm",
    "category": "autre",
    "specification": "ï¿½ 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.42
  },
  {
    "id": "gm-137",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/30/6282",
    "name": "Tï¿½ ï¿½gal ï¿½ sertir multicouche ï¿½ 26 mm",
    "category": "autre",
    "specification": "ï¿½ 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.69
  },
  {
    "id": "gm-138",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/11/9803",
    "name": "Tï¿½ ï¿½gal ï¿½ sertir multicouche ï¿½ 32 mm",
    "category": "autre",
    "specification": "ï¿½ 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.15
  },
  {
    "id": "gm-139",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/41/2783",
    "name": "Tï¿½ ï¿½gal ï¿½ sertir multicouche ï¿½ 40 mm",
    "category": "autre",
    "specification": "ï¿½ 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.17
  },
  {
    "id": "gm-140",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/15/1281",
    "name": "Tï¿½ ï¿½gal ï¿½ sertir multicouche ï¿½ 50 mm",
    "category": "autre",
    "specification": "ï¿½ 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 9.56
  },
  {
    "id": "gm-141",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/96/7949",
    "name": "Tï¿½ ï¿½gal ï¿½ sertir multicouche ï¿½ 63 mm",
    "category": "autre",
    "specification": "ï¿½ 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.62
  },
  {
    "id": "gm-142",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/51/9660",
    "name": "Raccord droit ï¿½ sertir multicouche ï¿½ 16 mm",
    "category": "autre",
    "specification": "ï¿½ 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.78
  },
  {
    "id": "gm-143",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/33/4510",
    "name": "Raccord droit ï¿½ sertir multicouche ï¿½ 20 mm",
    "category": "autre",
    "specification": "ï¿½ 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.99
  },
  {
    "id": "gm-144",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/86/8004",
    "name": "Raccord droit ï¿½ sertir multicouche ï¿½ 26 mm",
    "category": "autre",
    "specification": "ï¿½ 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.47
  },
  {
    "id": "gm-145",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/47/9479",
    "name": "Raccord droit ï¿½ sertir multicouche ï¿½ 32 mm",
    "category": "autre",
    "specification": "ï¿½ 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.03
  },
  {
    "id": "gm-146",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/35/1169",
    "name": "Raccord droit ï¿½ sertir multicouche ï¿½ 40 mm",
    "category": "autre",
    "specification": "ï¿½ 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 4.27
  },
  {
    "id": "gm-147",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/91/7974",
    "name": "Raccord droit ï¿½ sertir multicouche ï¿½ 50 mm",
    "category": "autre",
    "specification": "ï¿½ 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 12.06
  },
  {
    "id": "gm-148",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/66/7379",
    "name": "Raccord droit ï¿½ sertir multicouche ï¿½ 63 mm",
    "category": "autre",
    "specification": "ï¿½ 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.52
  },
  {
    "id": "gm-149",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/76/3569",
    "name": "Distributeur sanitaire laiton ï¿½ 16 mm",
    "category": "autre",
    "specification": "ï¿½ 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.31
  },
  {
    "id": "gm-150",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/10/8986",
    "name": "Distributeur sanitaire laiton ï¿½ 20 mm",
    "category": "autre",
    "specification": "ï¿½ 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.42
  },
  {
    "id": "gm-151",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/61/5908",
    "name": "Distributeur sanitaire laiton ï¿½ 26 mm",
    "category": "autre",
    "specification": "ï¿½ 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.46
  },
  {
    "id": "gm-152",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/54/1372",
    "name": "Distributeur sanitaire laiton ï¿½ 32 mm",
    "category": "autre",
    "specification": "ï¿½ 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.09
  },
  {
    "id": "gm-153",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/75/6952",
    "name": "Distributeur sanitaire laiton ï¿½ 40 mm",
    "category": "autre",
    "specification": "ï¿½ 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.39
  },
  {
    "id": "gm-154",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/34/9709",
    "name": "Distributeur sanitaire laiton ï¿½ 50 mm",
    "category": "autre",
    "specification": "ï¿½ 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.53
  },
  {
    "id": "gm-155",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/90/8521",
    "name": "Distributeur sanitaire laiton ï¿½ 63 mm",
    "category": "autre",
    "specification": "ï¿½ 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.18
  },
  {
    "id": "gm-156",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/31/2458",
    "name": "Vanne de sectionnement ï¿½ 16 mm",
    "category": "autre",
    "specification": "ï¿½ 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 10.46
  },
  {
    "id": "gm-157",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/64/7151",
    "name": "Vanne de sectionnement ï¿½ 20 mm",
    "category": "autre",
    "specification": "ï¿½ 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.01
  },
  {
    "id": "gm-158",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/93/9864",
    "name": "Vanne de sectionnement ï¿½ 26 mm",
    "category": "autre",
    "specification": "ï¿½ 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.94
  },
  {
    "id": "gm-159",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/44/7431",
    "name": "Vanne de sectionnement ï¿½ 32 mm",
    "category": "autre",
    "specification": "ï¿½ 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.09
  },
  {
    "id": "gm-160",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/96/2650",
    "name": "Vanne de sectionnement ï¿½ 40 mm",
    "category": "autre",
    "specification": "ï¿½ 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.37
  },
  {
    "id": "gm-161",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/50/4235",
    "name": "Vanne de sectionnement ï¿½ 50 mm",
    "category": "autre",
    "specification": "ï¿½ 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.24
  },
  {
    "id": "gm-162",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/94/4703",
    "name": "Vanne de sectionnement ï¿½ 63 mm",
    "category": "autre",
    "specification": "ï¿½ 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.53
  },
  {
    "id": "gm-163",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/31/5923",
    "name": "Isolation tubulaire mousse PE ï¿½ 16 mm",
    "category": "autre",
    "specification": "ï¿½ 16 mm",
    "active": true,
    "unit": "m",
    "base_price": 4.17
  },
  {
    "id": "gm-164",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/50/9456",
    "name": "Isolation tubulaire mousse PE ï¿½ 20 mm",
    "category": "autre",
    "specification": "ï¿½ 20 mm",
    "active": true,
    "unit": "m",
    "base_price": 9.45
  },
  {
    "id": "gm-165",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/11/2876",
    "name": "Isolation tubulaire mousse PE ï¿½ 26 mm",
    "category": "autre",
    "specification": "ï¿½ 26 mm",
    "active": true,
    "unit": "m",
    "base_price": 13.17
  },
  {
    "id": "gm-166",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/95/4931",
    "name": "Isolation tubulaire mousse PE ï¿½ 32 mm",
    "category": "autre",
    "specification": "ï¿½ 32 mm",
    "active": true,
    "unit": "m",
    "base_price": 14.48
  },
  {
    "id": "gm-167",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/11/6086",
    "name": "Isolation tubulaire mousse PE ï¿½ 40 mm",
    "category": "autre",
    "specification": "ï¿½ 40 mm",
    "active": true,
    "unit": "m",
    "base_price": 9.31
  },
  {
    "id": "gm-168",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/17/9175",
    "name": "Isolation tubulaire mousse PE ï¿½ 50 mm",
    "category": "autre",
    "specification": "ï¿½ 50 mm",
    "active": true,
    "unit": "m",
    "base_price": 10.77
  },
  {
    "id": "gm-169",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/64/9022",
    "name": "Isolation tubulaire mousse PE ï¿½ 63 mm",
    "category": "autre",
    "specification": "ï¿½ 63 mm",
    "active": true,
    "unit": "m",
    "base_price": 13.78
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // GEBERIT â€” Sanitaire / Ã‰vacuation / BÃ¢ti-supports
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "geb-1",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-111.796.00.1",
    "name": "BÃ¢ti-support Geberit Duofix pour WC suspendu h=112cm",
    "category": "geberit_duofix",
    "specification": "h=112cm standard",
    "active": true,
    "unit": "p",
    "base_price": 285.00
  },
  {
    "id": "geb-2",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-111.300.00.5",
    "name": "BÃ¢ti-support Geberit Duofix pour WC suspendu h=82cm (combles)",
    "category": "geberit_duofix",
    "specification": "h=82cm combles",
    "active": true,
    "unit": "p",
    "base_price": 310.00
  },
  {
    "id": "geb-3",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-111.362.00.5",
    "name": "BÃ¢ti-support Geberit Duofix pour WC suspendu avec rÃ©servoir intÃ©grÃ©",
    "category": "geberit_duofix",
    "specification": "h=112cm rÃ©servoir intÃ©grÃ© Sigma 12cm",
    "active": true,
    "unit": "p",
    "base_price": 345.00
  },
  {
    "id": "geb-4",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-111.798.00.1",
    "name": "BÃ¢ti-support Geberit Duofix pour WC suspendu angle h=112cm",
    "category": "geberit_duofix",
    "specification": "h=112cm angle",
    "active": true,
    "unit": "p",
    "base_price": 320.00
  },
  {
    "id": "geb-5",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-458.103.00.1",
    "name": "BÃ¢ti-support Geberit Duofix pour lavabo",
    "category": "geberit_duofix",
    "specification": "lavabo h=50-57cm",
    "active": true,
    "unit": "p",
    "base_price": 198.00
  },
  {
    "id": "geb-6",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-461.332.00.1",
    "name": "BÃ¢ti-support Geberit Duofix pour urinoir",
    "category": "geberit_duofix",
    "specification": "urinoir h=112cm",
    "active": true,
    "unit": "p",
    "base_price": 265.00
  },
  {
    "id": "geb-7",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-152.573.11.1",
    "name": "Plaque de commande Geberit Sigma20 blanc alpin",
    "category": "geberit_duofix",
    "specification": "Sigma20 blanc",
    "active": true,
    "unit": "p",
    "base_price": 89.00
  },
  {
    "id": "geb-8",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-115.882.SQ.1",
    "name": "Plaque de commande Geberit Sigma30 chrome",
    "category": "geberit_duofix",
    "specification": "Sigma30 chrome",
    "active": true,
    "unit": "p",
    "base_price": 165.00
  },
  {
    "id": "geb-9",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-152.313.11.1",
    "name": "RÃ©servoir encastrÃ© Geberit UP320 6/3L",
    "category": "geberit_duofix",
    "specification": "UP320 6/3L",
    "active": true,
    "unit": "p",
    "base_price": 148.00
  },
  {
    "id": "geb-10",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-119.012.00.1",
    "name": "Siphon de sol Geberit CleanLine avec grille acier",
    "category": "geberit_evacuation",
    "specification": "DN 70/50 inox",
    "active": true,
    "unit": "p",
    "base_price": 185.00
  },
  {
    "id": "geb-11",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-150.652.46.1",
    "name": "Siphon de sol Geberit DN 50 PP",
    "category": "geberit_evacuation",
    "specification": "DN 50",
    "active": true,
    "unit": "p",
    "base_price": 42.00
  },
  {
    "id": "geb-12",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-150.652.46.2",
    "name": "Siphon de sol Geberit DN 70 PP",
    "category": "geberit_evacuation",
    "specification": "DN 70",
    "active": true,
    "unit": "p",
    "base_price": 52.00
  },
  // PE Drainage Pipes (Geberit Silent-db20 / Silent-PP)
  {
    "id": "geb-20",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.200.14.1",
    "name": "Tuyau Ã©vacuation PE Silent-db20 DN 32",
    "category": "evacuation_pe",
    "specification": "DN 32",
    "active": true,
    "unit": "m",
    "base_price": 8.40
  },
  {
    "id": "geb-21",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.200.16.1",
    "name": "Tuyau Ã©vacuation PE Silent-db20 DN 40",
    "category": "evacuation_pe",
    "specification": "DN 40",
    "active": true,
    "unit": "m",
    "base_price": 10.20
  },
  {
    "id": "geb-22",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.200.22.1",
    "name": "Tuyau Ã©vacuation PE Silent-db20 DN 50",
    "category": "evacuation_pe",
    "specification": "DN 50",
    "active": true,
    "unit": "m",
    "base_price": 12.80
  },
  {
    "id": "geb-23",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.200.28.1",
    "name": "Tuyau Ã©vacuation PE Silent-db20 DN 70",
    "category": "evacuation_pe",
    "specification": "DN 70",
    "active": true,
    "unit": "m",
    "base_price": 18.50
  },
  {
    "id": "geb-24",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.200.40.1",
    "name": "Tuyau Ã©vacuation PE Silent-db20 DN 90",
    "category": "evacuation_pe",
    "specification": "DN 90",
    "active": true,
    "unit": "m",
    "base_price": 24.60
  },
  {
    "id": "geb-25",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.200.53.1",
    "name": "Tuyau Ã©vacuation PE Silent-db20 DN 110",
    "category": "evacuation_pe",
    "specification": "DN 110",
    "active": true,
    "unit": "m",
    "base_price": 32.80
  },
  {
    "id": "geb-26",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.200.66.1",
    "name": "Tuyau Ã©vacuation PE Silent-db20 DN 125",
    "category": "evacuation_pe",
    "specification": "DN 125",
    "active": true,
    "unit": "m",
    "base_price": 42.00
  },
  {
    "id": "geb-27",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.200.79.1",
    "name": "Tuyau Ã©vacuation PE Silent-db20 DN 160",
    "category": "evacuation_pe",
    "specification": "DN 160",
    "active": true,
    "unit": "m",
    "base_price": 68.00
  },
  // Coudes PE Ã©vacuation
  {
    "id": "geb-30",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.050.14.1",
    "name": "Coude 87Â° PE Ã©vacuation DN 32",
    "category": "evacuation_pe",
    "specification": "DN 32 87Â°",
    "active": true,
    "unit": "p",
    "base_price": 4.80
  },
  {
    "id": "geb-31",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.050.22.1",
    "name": "Coude 87Â° PE Ã©vacuation DN 50",
    "category": "evacuation_pe",
    "specification": "DN 50 87Â°",
    "active": true,
    "unit": "p",
    "base_price": 7.20
  },
  {
    "id": "geb-32",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.050.53.1",
    "name": "Coude 87Â° PE Ã©vacuation DN 110",
    "category": "evacuation_pe",
    "specification": "DN 110 87Â°",
    "active": true,
    "unit": "p",
    "base_price": 18.40
  },
  {
    "id": "geb-33",
    "supplier": { "code": "GEB", "name": "Geberit" },
    "reference": "GEB-393.060.53.1",
    "name": "Raccord en T PE Ã©vacuation DN 110/50",
    "category": "evacuation_pe",
    "specification": "DN 110/50",
    "active": true,
    "unit": "p",
    "base_price": 24.60
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // CHAUDIÃˆRES Ã€ CONDENSATION (Viessmann / Vaillant equivalents)
  // Prix indicatifs matÃ©riel fourni-posÃ© (hors main-d'oeuvre)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "chd-1",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "CHD-COND-15KW",
    "name": "ChaudiÃ¨re Ã  condensation gaz murale 15 kW",
    "category": "chaudiere",
    "specification": "15 kW condensation gaz",
    "active": true,
    "unit": "p",
    "base_price": 1850.00
  },
  {
    "id": "chd-2",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "CHD-COND-18KW",
    "name": "ChaudiÃ¨re Ã  condensation gaz murale 18 kW",
    "category": "chaudiere",
    "specification": "18 kW condensation gaz",
    "active": true,
    "unit": "p",
    "base_price": 2100.00
  },
  {
    "id": "chd-3",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "CHD-COND-24KW",
    "name": "ChaudiÃ¨re Ã  condensation gaz murale 24 kW",
    "category": "chaudiere",
    "specification": "24 kW condensation gaz",
    "active": true,
    "unit": "p",
    "base_price": 2450.00
  },
  {
    "id": "chd-4",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "CHD-COND-30KW",
    "name": "ChaudiÃ¨re Ã  condensation gaz murale 30 kW",
    "category": "chaudiere",
    "specification": "30 kW condensation gaz",
    "active": true,
    "unit": "p",
    "base_price": 2950.00
  },
  {
    "id": "chd-5",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "CHD-COND-35KW",
    "name": "ChaudiÃ¨re Ã  condensation gaz murale 35 kW",
    "category": "chaudiere",
    "specification": "35 kW condensation gaz",
    "active": true,
    "unit": "p",
    "base_price": 3400.00
  },
  {
    "id": "chd-6",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "CHD-COND-45KW",
    "name": "ChaudiÃ¨re Ã  condensation gaz murale 45 kW",
    "category": "chaudiere",
    "specification": "45 kW condensation gaz",
    "active": true,
    "unit": "p",
    "base_price": 4100.00
  },
  {
    "id": "chd-7",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "CHD-SOL-24KW",
    "name": "ChaudiÃ¨re Ã  condensation gaz sol 24 kW",
    "category": "chaudiere",
    "specification": "24 kW condensation gaz sol",
    "active": true,
    "unit": "p",
    "base_price": 3200.00
  },
  {
    "id": "chd-8",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "CHD-SOL-40KW",
    "name": "ChaudiÃ¨re Ã  condensation gaz sol 40 kW",
    "category": "chaudiere",
    "specification": "40 kW condensation gaz sol",
    "active": true,
    "unit": "p",
    "base_price": 4800.00
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // BALLONS ECS (Eau Chaude Sanitaire)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "ecs-1",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "ECS-80L",
    "name": "Ballon eau chaude sanitaire 80 litres",
    "category": "ballon_ecs",
    "specification": "80 L",
    "active": true,
    "unit": "p",
    "base_price": 480.00
  },
  {
    "id": "ecs-2",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "ECS-100L",
    "name": "Ballon eau chaude sanitaire 100 litres",
    "category": "ballon_ecs",
    "specification": "100 L",
    "active": true,
    "unit": "p",
    "base_price": 580.00
  },
  {
    "id": "ecs-3",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "ECS-150L",
    "name": "Ballon eau chaude sanitaire 150 litres",
    "category": "ballon_ecs",
    "specification": "150 L",
    "active": true,
    "unit": "p",
    "base_price": 720.00
  },
  {
    "id": "ecs-4",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "ECS-200L",
    "name": "Ballon eau chaude sanitaire 200 litres",
    "category": "ballon_ecs",
    "specification": "200 L",
    "active": true,
    "unit": "p",
    "base_price": 920.00
  },
  {
    "id": "ecs-5",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "ECS-300L",
    "name": "Ballon eau chaude sanitaire 300 litres",
    "category": "ballon_ecs",
    "specification": "300 L",
    "active": true,
    "unit": "p",
    "base_price": 1350.00
  },
  {
    "id": "ecs-6",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "ECS-500L",
    "name": "Ballon eau chaude sanitaire 500 litres",
    "category": "ballon_ecs",
    "specification": "500 L",
    "active": true,
    "unit": "p",
    "base_price": 2200.00
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // RADIATEURS PANNEAU (quantitÃ© toujours null â€” demander Ã  l'utilisateur)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "rad-1",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "RAD-11-600x600",
    "name": "Radiateur panneau simple type 11 h=600 l=600mm",
    "category": "radiateur",
    "specification": "Type 11 H600 L600",
    "active": true,
    "unit": "p",
    "base_price": 145.00
  },
  {
    "id": "rad-2",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "RAD-21-600x800",
    "name": "Radiateur panneau double type 21 h=600 l=800mm",
    "category": "radiateur",
    "specification": "Type 21 H600 L800",
    "active": true,
    "unit": "p",
    "base_price": 195.00
  },
  {
    "id": "rad-3",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "RAD-22-600x1000",
    "name": "Radiateur panneau double type 22 h=600 l=1000mm",
    "category": "radiateur",
    "specification": "Type 22 H600 L1000",
    "active": true,
    "unit": "p",
    "base_price": 245.00
  },
  {
    "id": "rad-4",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "RAD-22-600x1200",
    "name": "Radiateur panneau double type 22 h=600 l=1200mm",
    "category": "radiateur",
    "specification": "Type 22 H600 L1200",
    "active": true,
    "unit": "p",
    "base_price": 285.00
  },
  {
    "id": "rad-5",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "RAD-22-900x1000",
    "name": "Radiateur panneau double type 22 h=900 l=1000mm",
    "category": "radiateur",
    "specification": "Type 22 H900 L1000",
    "active": true,
    "unit": "p",
    "base_price": 320.00
  },
  {
    "id": "rad-6",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "RAD-33-600x1000",
    "name": "Radiateur panneau triple type 33 h=600 l=1000mm",
    "category": "radiateur",
    "specification": "Type 33 H600 L1000",
    "active": true,
    "unit": "p",
    "base_price": 365.00
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // ROBINETTERIE / VANNES
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "rob-1",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-ROB-VB-15",
    "name": "Robinet d'arrÃªt Ã  bille Ã˜ 15 mm Ã  sertir inox",
    "category": "robinetterie",
    "specification": "Ã˜ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 48.50
  },
  {
    "id": "rob-2",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-ROB-VB-18",
    "name": "Robinet d'arrÃªt Ã  bille Ã˜ 18 mm Ã  sertir inox",
    "category": "robinetterie",
    "specification": "Ã˜ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 62.00
  },
  {
    "id": "rob-3",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-ROB-VB-22",
    "name": "Robinet d'arrÃªt Ã  bille Ã˜ 22 mm Ã  sertir inox",
    "category": "robinetterie",
    "specification": "Ã˜ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 78.00
  },
  {
    "id": "rob-4",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-ROB-VB-28",
    "name": "Robinet d'arrÃªt Ã  bille Ã˜ 28 mm Ã  sertir inox",
    "category": "robinetterie",
    "specification": "Ã˜ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 98.00
  },
  {
    "id": "rob-5",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-ROB-VB-35",
    "name": "Robinet d'arrÃªt Ã  bille Ã˜ 35 mm Ã  sertir inox",
    "category": "robinetterie",
    "specification": "Ã˜ 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 138.00
  },
  {
    "id": "rob-6",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-ROB-VB-42",
    "name": "Robinet d'arrÃªt Ã  bille Ã˜ 42 mm Ã  sertir inox",
    "category": "robinetterie",
    "specification": "Ã˜ 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 185.00
  },
  {
    "id": "rob-7",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-ROB-VB-54",
    "name": "Robinet d'arrÃªt Ã  bille Ã˜ 54 mm Ã  sertir inox",
    "category": "robinetterie",
    "specification": "Ã˜ 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 245.00
  },
  {
    "id": "rob-8",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-MIX-LAV-12",
    "name": "Mitigeur lavabo monocommande 1/2\"",
    "category": "robinetterie",
    "specification": "1/2\" lavabo",
    "active": true,
    "unit": "p",
    "base_price": 185.00
  },
  {
    "id": "rob-9",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-MIX-BAI-12",
    "name": "Mitigeur baignoire / douche monocommande",
    "category": "robinetterie",
    "specification": "1/2\" bain/douche",
    "active": true,
    "unit": "p",
    "base_price": 245.00
  },
  {
    "id": "rob-10",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-MIX-CUI-12",
    "name": "Mitigeur cuisine monocommande bec haut",
    "category": "robinetterie",
    "specification": "1/2\" cuisine",
    "active": true,
    "unit": "p",
    "base_price": 210.00
  },
  {
    "id": "rob-11",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-ROB-VDET",
    "name": "RÃ©ducteur de pression rÃ©glable 1/2\"â€“2\" 1.5â€“6 bar",
    "category": "robinetterie",
    "specification": "1/2\"-2\" 1.5-6 bar",
    "active": true,
    "unit": "p",
    "base_price": 165.00
  },
  {
    "id": "rob-12",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-ROB-CLAPET",
    "name": "Clapet anti-retour Ã˜ 15 mm Ã  sertir",
    "category": "robinetterie",
    "specification": "Ã˜ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 38.00
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // CIRCULATEURS / POMPES
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "cir-1",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "CIR-GRUNDFOS-UPS",
    "name": "Circulateur Grundfos UPS 25-40 1/2\" DN 25",
    "category": "circulateur",
    "specification": "DN 25 H=4m Q=2.5m3/h",
    "active": true,
    "unit": "p",
    "base_price": 285.00
  },
  {
    "id": "cir-2",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "CIR-GRUNDFOS-UPS60",
    "name": "Circulateur Grundfos UPS 25-60 1/2\" DN 25",
    "category": "circulateur",
    "specification": "DN 25 H=6m Q=3m3/h",
    "active": true,
    "unit": "p",
    "base_price": 345.00
  },
  {
    "id": "cir-3",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "CIR-WILO-STRATOS",
    "name": "Circulateur Wilo Stratos PICO 25/1-6 DN 25 Ã  vitesse variable",
    "category": "circulateur",
    "specification": "DN 25 vitesse variable EC",
    "active": true,
    "unit": "p",
    "base_price": 480.00
  },
  {
    "id": "cir-4",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "CIR-WILO-PARA",
    "name": "Circulateur Wilo Para 25/6 DN 25 Classe A",
    "category": "circulateur",
    "specification": "DN 25 Classe A",
    "active": true,
    "unit": "p",
    "base_price": 395.00
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // NOURRICE / COLLECTEUR / DISTRIBUTION
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "nou-1",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-NOU-2P",
    "name": "Nourrice distribution 2 dÃ©parts Ã˜ 22 mm inox",
    "category": "nourrice",
    "specification": "2 dÃ©parts Ã˜ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 145.00
  },
  {
    "id": "nou-2",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-NOU-3P",
    "name": "Nourrice distribution 3 dÃ©parts Ã˜ 22 mm inox",
    "category": "nourrice",
    "specification": "3 dÃ©parts Ã˜ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 185.00
  },
  {
    "id": "nou-3",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-NOU-4P",
    "name": "Nourrice distribution 4 dÃ©parts Ã˜ 22 mm inox",
    "category": "nourrice",
    "specification": "4 dÃ©parts Ã˜ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 220.00
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // ROBINETS DE RADIATEUR / TÃŠTES THERMOSTATIQUES
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "tth-1",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-CORPS-RAD-15",
    "name": "Corps thermostatique pour radiateur Ã˜ 15 mm",
    "category": "robinetterie",
    "specification": "Ã˜ 15 mm angle",
    "active": true,
    "unit": "p",
    "base_price": 42.00
  },
  {
    "id": "tth-2",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-TETE-THERM",
    "name": "TÃªte thermostatique radiateur rÃ©glable 6-28Â°C",
    "category": "robinetterie",
    "specification": "6-28Â°C M30x1.5",
    "active": true,
    "unit": "p",
    "base_price": 28.00
  },
  {
    "id": "tth-3",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-RETOUR-RAD",
    "name": "Robinet de retour pour radiateur Ã˜ 15 mm",
    "category": "robinetterie",
    "specification": "Ã˜ 15 mm angle retour",
    "active": true,
    "unit": "p",
    "base_price": 38.00
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // APPAREILS SANITAIRES (lavabos, WC, douches)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "san-1",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-LAV-BASE",
    "name": "Lavabo suspendu cÃ©ramique blanc 60cm avec trop-plein",
    "category": "appareil_sanitaire",
    "specification": "60 cm blanc",
    "active": true,
    "unit": "p",
    "base_price": 185.00
  },
  {
    "id": "san-2",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-WC-SUSP",
    "name": "Cuvette WC suspendu cÃ©ramique blanc avec abattant",
    "category": "appareil_sanitaire",
    "specification": "WC suspendu blanc",
    "active": true,
    "unit": "p",
    "base_price": 265.00
  },
  {
    "id": "san-3",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-WC-POSE",
    "name": "Cuvette WC Ã  poser cÃ©ramique blanc avec abattant",
    "category": "appareil_sanitaire",
    "specification": "WC Ã  poser blanc",
    "active": true,
    "unit": "p",
    "base_price": 195.00
  },
  {
    "id": "san-4",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-BAC-DOUCH",
    "name": "Bac Ã  douche rÃ©sine 80x80cm avec bonde",
    "category": "appareil_sanitaire",
    "specification": "80x80 cm",
    "active": true,
    "unit": "p",
    "base_price": 285.00
  },
  {
    "id": "san-5",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN-BAC-DOUCH-90",
    "name": "Bac Ã  douche rÃ©sine 90x90cm avec bonde",
    "category": "appareil_sanitaire",
    "specification": "90x90 cm",
    "active": true,
    "unit": "p",
    "base_price": 320.00
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // DÃ‰POSE / DÃ‰MONTAGE (forfaits main-d'oeuvre inclus)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "dep-1",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "DEP-TUYAUX",
    "name": "DÃ©pose et Ã©vacuation conduite existante",
    "category": "depose",
    "specification": "forfait dÃ©pose",
    "active": true,
    "unit": "m",
    "base_price": 35.00
  },
  {
    "id": "dep-2",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "DEP-CHAUD",
    "name": "DÃ©pose chaudiÃ¨re ancienne et Ã©vacuation",
    "category": "depose",
    "specification": "forfait chaudiÃ¨re",
    "active": true,
    "unit": "p",
    "base_price": 280.00
  },
  {
    "id": "dep-3",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "DEP-RAD",
    "name": "DÃ©pose radiateur existant et Ã©vacuation",
    "category": "depose",
    "specification": "forfait radiateur",
    "active": true,
    "unit": "p",
    "base_price": 95.00
  },
  {
    "id": "dep-4",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "DEP-APPSAN",
    "name": "DÃ©pose appareil sanitaire et Ã©vacuation",
    "category": "depose",
    "specification": "forfait appareil sanitaire",
    "active": true,
    "unit": "p",
    "base_price": 120.00
  },
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // MANCHONS / RACCORDS (corriger catÃ©gorie "autre" â†’ "manchon")
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    "id": "nsb-m1",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-MANCH-15",
    "name": "Manchon Ã©gal Ã  sertir inox Ã˜ 15 mm",
    "category": "manchon",
    "specification": "Ã˜ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 20.28
  },
  {
    "id": "nsb-m2",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-MANCH-18",
    "name": "Manchon Ã©gal Ã  sertir inox Ã˜ 18 mm",
    "category": "manchon",
    "specification": "Ã˜ 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 24.15
  },
  {
    "id": "nsb-m3",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-MANCH-22",
    "name": "Manchon Ã©gal Ã  sertir inox Ã˜ 22 mm",
    "category": "manchon",
    "specification": "Ã˜ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 28.90
  },
  {
    "id": "nsb-m4",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-MANCH-28",
    "name": "Manchon Ã©gal Ã  sertir inox Ã˜ 28 mm",
    "category": "manchon",
    "specification": "Ã˜ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 35.40
  },
  {
    "id": "nsb-m5",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-MANCH-RED-22-15",
    "name": "Manchon rÃ©duit Ã  sertir inox Ã˜ 22/15 mm",
    "category": "manchon",
    "specification": "Ã˜ 22/15 mm",
    "active": true,
    "unit": "p",
    "base_price": 32.00
  },
  {
    "id": "nsb-m6",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-MANCH-RED-28-22",
    "name": "Manchon rÃ©duit Ã  sertir inox Ã˜ 28/22 mm",
    "category": "manchon",
    "specification": "Ã˜ 28/22 mm",
    "active": true,
    "unit": "p",
    "base_price": 41.00
  },
  {
    "id": "nsb-t1",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-TE-15",
    "name": "TÃ© Ã©gal Ã  sertir inox Ã˜ 15 mm",
    "category": "manchon",
    "specification": "Ã˜ 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 28.50
  },
  {
    "id": "nsb-t2",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-TE-22",
    "name": "TÃ© Ã©gal Ã  sertir inox Ã˜ 22 mm",
    "category": "manchon",
    "specification": "Ã˜ 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 38.70
  },
  {
    "id": "nsb-t3",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-TE-28",
    "name": "TÃ© Ã©gal Ã  sertir inox Ã˜ 28 mm",
    "category": "manchon",
    "specification": "Ã˜ 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 52.00
  }
];


