export const SUPPLIERS = {
  NSB: { code: "NSB", name: "Nussbaum" },
  ST: { code: "ST", name: "Sanitas Troesch" },
  GM: { code: "GM", name: "Getaz Miauton" },
};

export const MOCK_CATALOGUE = [
  {
    "id": "nsb-1",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9953-12",
    "name": "Tuyau acier inox 1.4521 Optipress � 12 mm",
    "category": "tuyau_inox",
    "specification": "� 12 mm",
    "active": true,
    "unit": "m",
    "base_price": 15.21
  },
  {
    "id": "nsb-2",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6673-15",
    "name": "Tuyau acier inox 1.4521 Optipress � 15 mm",
    "category": "tuyau_inox",
    "specification": "� 15 mm",
    "active": true,
    "unit": "m",
    "base_price": 31.00
  },
  {
    "id": "nsb-3",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1717-18",
    "name": "Tuyau acier inox 1.4521 Optipress � 18 mm",
    "category": "tuyau_inox",
    "specification": "� 18 mm",
    "active": true,
    "unit": "m",
    "base_price": 29.26
  },
  {
    "id": "nsb-4",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1129-22",
    "name": "Tuyau acier inox 1.4521 Optipress � 22 mm",
    "category": "tuyau_inox",
    "specification": "� 22 mm",
    "active": true,
    "unit": "m",
    "base_price": 25.77
  },
  {
    "id": "nsb-5",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2051-28",
    "name": "Tuyau acier inox 1.4521 Optipress � 28 mm",
    "category": "tuyau_inox",
    "specification": "� 28 mm",
    "active": true,
    "unit": "m",
    "base_price": 26.00
  },
  {
    "id": "nsb-6",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4473-35",
    "name": "Tuyau acier inox 1.4521 Optipress � 35 mm",
    "category": "tuyau_inox",
    "specification": "� 35 mm",
    "active": true,
    "unit": "m",
    "base_price": 31.55
  },
  {
    "id": "nsb-7",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1214-42",
    "name": "Tuyau acier inox 1.4521 Optipress � 42 mm",
    "category": "tuyau_inox",
    "specification": "� 42 mm",
    "active": true,
    "unit": "m",
    "base_price": 11.75
  },
  {
    "id": "nsb-8",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2103-54",
    "name": "Tuyau acier inox 1.4521 Optipress � 54 mm",
    "category": "tuyau_inox",
    "specification": "� 54 mm",
    "active": true,
    "unit": "m",
    "base_price": 11.99
  },
  {
    "id": "nsb-9",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8567-12",
    "name": "Coude 90� � sertir inox � 12 mm",
    "category": "coude_sertir",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.78
  },
  {
    "id": "nsb-10",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2056-15",
    "name": "Coude 90� � sertir inox � 15 mm",
    "category": "coude_sertir",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.47
  },
  {
    "id": "nsb-11",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9614-18",
    "name": "Coude 90� � sertir inox � 18 mm",
    "category": "coude_sertir",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.93
  },
  {
    "id": "nsb-12",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6566-22",
    "name": "Coude 90� � sertir inox � 22 mm",
    "category": "coude_sertir",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 22.37
  },
  {
    "id": "nsb-13",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8101-28",
    "name": "Coude 90� � sertir inox � 28 mm",
    "category": "coude_sertir",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 33.64
  },
  {
    "id": "nsb-14",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7514-35",
    "name": "Coude 90� � sertir inox � 35 mm",
    "category": "coude_sertir",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 26.89
  },
  {
    "id": "nsb-15",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2545-42",
    "name": "Coude 90� � sertir inox � 42 mm",
    "category": "coude_sertir",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 25.32
  },
  {
    "id": "nsb-16",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2766-54",
    "name": "Coude 90� � sertir inox � 54 mm",
    "category": "coude_sertir",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.75
  },
  {
    "id": "nsb-17",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8014-12",
    "name": "Coude 45� � sertir inox � 12 mm",
    "category": "coude_sertir",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 34.15
  },
  {
    "id": "nsb-18",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7954-15",
    "name": "Coude 45� � sertir inox � 15 mm",
    "category": "coude_sertir",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.03
  },
  {
    "id": "nsb-19",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6669-18",
    "name": "Coude 45� � sertir inox � 18 mm",
    "category": "coude_sertir",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.43
  },
  {
    "id": "nsb-20",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-3443-22",
    "name": "Coude 45� � sertir inox � 22 mm",
    "category": "coude_sertir",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.21
  },
  {
    "id": "nsb-21",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6704-28",
    "name": "Coude 45� � sertir inox � 28 mm",
    "category": "coude_sertir",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 27.56
  },
  {
    "id": "nsb-22",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1936-35",
    "name": "Coude 45� � sertir inox � 35 mm",
    "category": "coude_sertir",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.40
  },
  {
    "id": "nsb-23",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5440-42",
    "name": "Coude 45� � sertir inox � 42 mm",
    "category": "coude_sertir",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.28
  },
  {
    "id": "nsb-24",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4045-54",
    "name": "Coude 45� � sertir inox � 54 mm",
    "category": "coude_sertir",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.93
  },
  {
    "id": "nsb-25",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7462-12",
    "name": "Manchon � sertir inox � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.03
  },
  {
    "id": "nsb-26",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8174-15",
    "name": "Manchon � sertir inox � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 20.28
  },
  {
    "id": "nsb-27",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9483-18",
    "name": "Manchon � sertir inox � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.76
  },
  {
    "id": "nsb-28",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2981-22",
    "name": "Manchon � sertir inox � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.64
  },
  {
    "id": "nsb-29",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8787-28",
    "name": "Manchon � sertir inox � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.13
  },
  {
    "id": "nsb-30",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2168-35",
    "name": "Manchon � sertir inox � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.71
  },
  {
    "id": "nsb-31",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8482-42",
    "name": "Manchon � sertir inox � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 12.90
  },
  {
    "id": "nsb-32",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2905-54",
    "name": "Manchon � sertir inox � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.82
  },
  {
    "id": "nsb-33",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6413-12",
    "name": "Manchon de r�duction inox � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.13
  },
  {
    "id": "nsb-34",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8565-15",
    "name": "Manchon de r�duction inox � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 20.83
  },
  {
    "id": "nsb-35",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9963-18",
    "name": "Manchon de r�duction inox � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 10.69
  },
  {
    "id": "nsb-36",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1341-22",
    "name": "Manchon de r�duction inox � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 30.37
  },
  {
    "id": "nsb-37",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9579-28",
    "name": "Manchon de r�duction inox � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 31.29
  },
  {
    "id": "nsb-38",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8404-35",
    "name": "Manchon de r�duction inox � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 24.49
  },
  {
    "id": "nsb-39",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9491-42",
    "name": "Manchon de r�duction inox � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 34.40
  },
  {
    "id": "nsb-40",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5767-54",
    "name": "Manchon de r�duction inox � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 32.93
  },
  {
    "id": "nsb-41",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4962-12",
    "name": "T� � sertir inox � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.34
  },
  {
    "id": "nsb-42",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2162-15",
    "name": "T� � sertir inox � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 28.60
  },
  {
    "id": "nsb-43",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2837-18",
    "name": "T� � sertir inox � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 12.14
  },
  {
    "id": "nsb-44",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5497-22",
    "name": "T� � sertir inox � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 30.23
  },
  {
    "id": "nsb-45",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4535-28",
    "name": "T� � sertir inox � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 30.67
  },
  {
    "id": "nsb-46",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7465-35",
    "name": "T� � sertir inox � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.73
  },
  {
    "id": "nsb-47",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7658-42",
    "name": "T� � sertir inox � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 27.76
  },
  {
    "id": "nsb-48",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9708-54",
    "name": "T� � sertir inox � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.89
  },
  {
    "id": "nsb-49",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4873-12",
    "name": "Collier de fixation isophonique � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 31.38
  },
  {
    "id": "nsb-50",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-2295-15",
    "name": "Collier de fixation isophonique � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.26
  },
  {
    "id": "nsb-51",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6783-18",
    "name": "Collier de fixation isophonique � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.85
  },
  {
    "id": "nsb-52",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6189-22",
    "name": "Collier de fixation isophonique � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 32.37
  },
  {
    "id": "nsb-53",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5180-28",
    "name": "Collier de fixation isophonique � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 9.61
  },
  {
    "id": "nsb-54",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-4289-35",
    "name": "Collier de fixation isophonique � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 27.46
  },
  {
    "id": "nsb-55",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9433-42",
    "name": "Collier de fixation isophonique � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.67
  },
  {
    "id": "nsb-56",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7673-54",
    "name": "Collier de fixation isophonique � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.91
  },
  {
    "id": "nsb-57",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-8847-12",
    "name": "Coquille isolante en PIR avec gaine PVC � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "m",
    "base_price": 21.49
  },
  {
    "id": "nsb-58",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-5795-15",
    "name": "Coquille isolante en PIR avec gaine PVC � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "m",
    "base_price": 27.31
  },
  {
    "id": "nsb-59",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-9244-18",
    "name": "Coquille isolante en PIR avec gaine PVC � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "m",
    "base_price": 14.73
  },
  {
    "id": "nsb-60",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1929-22",
    "name": "Coquille isolante en PIR avec gaine PVC � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "m",
    "base_price": 32.22
  },
  {
    "id": "nsb-61",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-1965-28",
    "name": "Coquille isolante en PIR avec gaine PVC � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "m",
    "base_price": 6.73
  },
  {
    "id": "nsb-62",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-3073-35",
    "name": "Coquille isolante en PIR avec gaine PVC � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "m",
    "base_price": 16.70
  },
  {
    "id": "nsb-63",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-6802-42",
    "name": "Coquille isolante en PIR avec gaine PVC � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "m",
    "base_price": 31.05
  },
  {
    "id": "nsb-64",
    "supplier": { "code": "NSB", "name": "Nussbaum" },
    "reference": "NSB-7676-54",
    "name": "Coquille isolante en PIR avec gaine PVC � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "m",
    "base_price": 12.37
  },
  {
    "id": "st-65",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.774268",
    "name": "Tube cuivre en barre �croui � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "m",
    "base_price": 9.61
  },
  {
    "id": "st-66",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.862942",
    "name": "Tube cuivre en barre �croui � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "m",
    "base_price": 21.68
  },
  {
    "id": "st-67",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.595027",
    "name": "Tube cuivre en barre �croui � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "m",
    "base_price": 12.98
  },
  {
    "id": "st-68",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.216366",
    "name": "Tube cuivre en barre �croui � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "m",
    "base_price": 12.01
  },
  {
    "id": "st-69",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.832567",
    "name": "Tube cuivre en barre �croui � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "m",
    "base_price": 4.16
  },
  {
    "id": "st-70",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.492687",
    "name": "Tube cuivre en barre �croui � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "m",
    "base_price": 6.37
  },
  {
    "id": "st-71",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.793748",
    "name": "Tube cuivre en barre �croui � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "m",
    "base_price": 4.18
  },
  {
    "id": "st-72",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.888565",
    "name": "Tube cuivre en barre �croui � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "m",
    "base_price": 19.53
  },
  {
    "id": "st-73",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.292644",
    "name": "Coude 90� cuivre � souder � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.46
  },
  {
    "id": "st-74",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.247341",
    "name": "Coude 90� cuivre � souder � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.51
  },
  {
    "id": "st-75",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.658747",
    "name": "Coude 90� cuivre � souder � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 9.55
  },
  {
    "id": "st-76",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.661115",
    "name": "Coude 90� cuivre � souder � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.85
  },
  {
    "id": "st-77",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.269587",
    "name": "Coude 90� cuivre � souder � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 4.41
  },
  {
    "id": "st-78",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.768324",
    "name": "Coude 90� cuivre � souder � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.18
  },
  {
    "id": "st-79",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.720430",
    "name": "Coude 90� cuivre � souder � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.62
  },
  {
    "id": "st-80",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.657790",
    "name": "Coude 90� cuivre � souder � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.38
  },
  {
    "id": "st-81",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.403630",
    "name": "Manchon cuivre � souder � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.91
  },
  {
    "id": "st-82",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.537552",
    "name": "Manchon cuivre � souder � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.85
  },
  {
    "id": "st-83",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.813184",
    "name": "Manchon cuivre � souder � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.50
  },
  {
    "id": "st-84",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.800416",
    "name": "Manchon cuivre � souder � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.28
  },
  {
    "id": "st-85",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.611123",
    "name": "Manchon cuivre � souder � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.18
  },
  {
    "id": "st-86",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.319725",
    "name": "Manchon cuivre � souder � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.70
  },
  {
    "id": "st-87",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.293216",
    "name": "Manchon cuivre � souder � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.80
  },
  {
    "id": "st-88",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.159206",
    "name": "Manchon cuivre � souder � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.07
  },
  {
    "id": "st-89",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.188006",
    "name": "Raccord de transition bronze/cuivre � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.33
  },
  {
    "id": "st-90",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.795067",
    "name": "Raccord de transition bronze/cuivre � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 17.16
  },
  {
    "id": "st-91",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.693789",
    "name": "Raccord de transition bronze/cuivre � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.67
  },
  {
    "id": "st-92",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.358525",
    "name": "Raccord de transition bronze/cuivre � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.10
  },
  {
    "id": "st-93",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.853403",
    "name": "Raccord de transition bronze/cuivre � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.11
  },
  {
    "id": "st-94",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.883994",
    "name": "Raccord de transition bronze/cuivre � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 19.18
  },
  {
    "id": "st-95",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.998149",
    "name": "Raccord de transition bronze/cuivre � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 12.61
  },
  {
    "id": "st-96",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.237165",
    "name": "Raccord de transition bronze/cuivre � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.45
  },
  {
    "id": "st-97",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.871566",
    "name": "T� cuivre � souder � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.85
  },
  {
    "id": "st-98",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.706000",
    "name": "T� cuivre � souder � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.95
  },
  {
    "id": "st-99",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.428725",
    "name": "T� cuivre � souder � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.68
  },
  {
    "id": "st-100",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.681738",
    "name": "T� cuivre � souder � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.38
  },
  {
    "id": "st-101",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.562362",
    "name": "T� cuivre � souder � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.74
  },
  {
    "id": "st-102",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.190465",
    "name": "T� cuivre � souder � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.91
  },
  {
    "id": "st-103",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.546036",
    "name": "T� cuivre � souder � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 21.48
  },
  {
    "id": "st-104",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.492368",
    "name": "T� cuivre � souder � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.77
  },
  {
    "id": "st-105",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.813631",
    "name": "Vanne � bille laiton � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.10
  },
  {
    "id": "st-106",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.239486",
    "name": "Vanne � bille laiton � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.14
  },
  {
    "id": "st-107",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.527774",
    "name": "Vanne � bille laiton � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 9.10
  },
  {
    "id": "st-108",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.957037",
    "name": "Vanne � bille laiton � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.44
  },
  {
    "id": "st-109",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.957714",
    "name": "Vanne � bille laiton � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.36
  },
  {
    "id": "st-110",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.727018",
    "name": "Vanne � bille laiton � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.00
  },
  {
    "id": "st-111",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.510044",
    "name": "Vanne � bille laiton � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.79
  },
  {
    "id": "st-112",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.716503",
    "name": "Vanne � bille laiton � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.83
  },
  {
    "id": "st-113",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.616711",
    "name": "Collier simple M8 � 12 mm",
    "category": "autre",
    "specification": "� 12 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.50
  },
  {
    "id": "st-114",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.601923",
    "name": "Collier simple M8 � 15 mm",
    "category": "autre",
    "specification": "� 15 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.04
  },
  {
    "id": "st-115",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.278473",
    "name": "Collier simple M8 � 18 mm",
    "category": "autre",
    "specification": "� 18 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.41
  },
  {
    "id": "st-116",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.538613",
    "name": "Collier simple M8 � 22 mm",
    "category": "autre",
    "specification": "� 22 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.23
  },
  {
    "id": "st-117",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.737057",
    "name": "Collier simple M8 � 28 mm",
    "category": "autre",
    "specification": "� 28 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.97
  },
  {
    "id": "st-118",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.204215",
    "name": "Collier simple M8 � 35 mm",
    "category": "autre",
    "specification": "� 35 mm",
    "active": true,
    "unit": "p",
    "base_price": 20.95
  },
  {
    "id": "st-119",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.688098",
    "name": "Collier simple M8 � 42 mm",
    "category": "autre",
    "specification": "� 42 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.93
  },
  {
    "id": "st-120",
    "supplier": { "code": "ST", "name": "Sanitas Troesch" },
    "reference": "SAN.136669",
    "name": "Collier simple M8 � 54 mm",
    "category": "autre",
    "specification": "� 54 mm",
    "active": true,
    "unit": "p",
    "base_price": 18.63
  },
  {
    "id": "gm-121",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/85/1775",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc � 16 mm",
    "category": "autre",
    "specification": "� 16 mm",
    "active": true,
    "unit": "m",
    "base_price": 5.10
  },
  {
    "id": "gm-122",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/39/1766",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc � 20 mm",
    "category": "autre",
    "specification": "� 20 mm",
    "active": true,
    "unit": "m",
    "base_price": 5.01
  },
  {
    "id": "gm-123",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/43/1541",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc � 26 mm",
    "category": "autre",
    "specification": "� 26 mm",
    "active": true,
    "unit": "m",
    "base_price": 15.99
  },
  {
    "id": "gm-124",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/49/1204",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc � 32 mm",
    "category": "autre",
    "specification": "� 32 mm",
    "active": true,
    "unit": "m",
    "base_price": 13.35
  },
  {
    "id": "gm-125",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/87/7440",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc � 40 mm",
    "category": "autre",
    "specification": "� 40 mm",
    "active": true,
    "unit": "m",
    "base_price": 3.64
  },
  {
    "id": "gm-126",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/73/6051",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc � 50 mm",
    "category": "autre",
    "specification": "� 50 mm",
    "active": true,
    "unit": "m",
    "base_price": 5.48
  },
  {
    "id": "gm-127",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/76/4759",
    "name": "Tube multicouche PE-Xc/Al/PE-Xc � 63 mm",
    "category": "autre",
    "specification": "� 63 mm",
    "active": true,
    "unit": "m",
    "base_price": 10.77
  },
  {
    "id": "gm-128",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/60/2144",
    "name": "Coude 90� � sertir multicouche � 16 mm",
    "category": "autre",
    "specification": "� 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.62
  },
  {
    "id": "gm-129",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/49/6802",
    "name": "Coude 90� � sertir multicouche � 20 mm",
    "category": "autre",
    "specification": "� 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.11
  },
  {
    "id": "gm-130",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/74/3096",
    "name": "Coude 90� � sertir multicouche � 26 mm",
    "category": "autre",
    "specification": "� 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.12
  },
  {
    "id": "gm-131",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/10/8311",
    "name": "Coude 90� � sertir multicouche � 32 mm",
    "category": "autre",
    "specification": "� 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.60
  },
  {
    "id": "gm-132",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/67/1966",
    "name": "Coude 90� � sertir multicouche � 40 mm",
    "category": "autre",
    "specification": "� 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.71
  },
  {
    "id": "gm-133",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/98/8905",
    "name": "Coude 90� � sertir multicouche � 50 mm",
    "category": "autre",
    "specification": "� 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.07
  },
  {
    "id": "gm-134",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/99/7401",
    "name": "Coude 90� � sertir multicouche � 63 mm",
    "category": "autre",
    "specification": "� 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.46
  },
  {
    "id": "gm-135",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/97/6922",
    "name": "T� �gal � sertir multicouche � 16 mm",
    "category": "autre",
    "specification": "� 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.86
  },
  {
    "id": "gm-136",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/67/4019",
    "name": "T� �gal � sertir multicouche � 20 mm",
    "category": "autre",
    "specification": "� 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.42
  },
  {
    "id": "gm-137",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/30/6282",
    "name": "T� �gal � sertir multicouche � 26 mm",
    "category": "autre",
    "specification": "� 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.69
  },
  {
    "id": "gm-138",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/11/9803",
    "name": "T� �gal � sertir multicouche � 32 mm",
    "category": "autre",
    "specification": "� 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.15
  },
  {
    "id": "gm-139",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/41/2783",
    "name": "T� �gal � sertir multicouche � 40 mm",
    "category": "autre",
    "specification": "� 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 2.17
  },
  {
    "id": "gm-140",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/15/1281",
    "name": "T� �gal � sertir multicouche � 50 mm",
    "category": "autre",
    "specification": "� 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 9.56
  },
  {
    "id": "gm-141",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/96/7949",
    "name": "T� �gal � sertir multicouche � 63 mm",
    "category": "autre",
    "specification": "� 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.62
  },
  {
    "id": "gm-142",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/51/9660",
    "name": "Raccord droit � sertir multicouche � 16 mm",
    "category": "autre",
    "specification": "� 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 11.78
  },
  {
    "id": "gm-143",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/33/4510",
    "name": "Raccord droit � sertir multicouche � 20 mm",
    "category": "autre",
    "specification": "� 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.99
  },
  {
    "id": "gm-144",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/86/8004",
    "name": "Raccord droit � sertir multicouche � 26 mm",
    "category": "autre",
    "specification": "� 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 5.47
  },
  {
    "id": "gm-145",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/47/9479",
    "name": "Raccord droit � sertir multicouche � 32 mm",
    "category": "autre",
    "specification": "� 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.03
  },
  {
    "id": "gm-146",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/35/1169",
    "name": "Raccord droit � sertir multicouche � 40 mm",
    "category": "autre",
    "specification": "� 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 4.27
  },
  {
    "id": "gm-147",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/91/7974",
    "name": "Raccord droit � sertir multicouche � 50 mm",
    "category": "autre",
    "specification": "� 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 12.06
  },
  {
    "id": "gm-148",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/66/7379",
    "name": "Raccord droit � sertir multicouche � 63 mm",
    "category": "autre",
    "specification": "� 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.52
  },
  {
    "id": "gm-149",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/76/3569",
    "name": "Distributeur sanitaire laiton � 16 mm",
    "category": "autre",
    "specification": "� 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.31
  },
  {
    "id": "gm-150",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/10/8986",
    "name": "Distributeur sanitaire laiton � 20 mm",
    "category": "autre",
    "specification": "� 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.42
  },
  {
    "id": "gm-151",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/61/5908",
    "name": "Distributeur sanitaire laiton � 26 mm",
    "category": "autre",
    "specification": "� 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.46
  },
  {
    "id": "gm-152",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/54/1372",
    "name": "Distributeur sanitaire laiton � 32 mm",
    "category": "autre",
    "specification": "� 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 14.09
  },
  {
    "id": "gm-153",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/75/6952",
    "name": "Distributeur sanitaire laiton � 40 mm",
    "category": "autre",
    "specification": "� 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 6.39
  },
  {
    "id": "gm-154",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/34/9709",
    "name": "Distributeur sanitaire laiton � 50 mm",
    "category": "autre",
    "specification": "� 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 7.53
  },
  {
    "id": "gm-155",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/90/8521",
    "name": "Distributeur sanitaire laiton � 63 mm",
    "category": "autre",
    "specification": "� 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 15.18
  },
  {
    "id": "gm-156",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/31/2458",
    "name": "Vanne de sectionnement � 16 mm",
    "category": "autre",
    "specification": "� 16 mm",
    "active": true,
    "unit": "p",
    "base_price": 10.46
  },
  {
    "id": "gm-157",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/64/7151",
    "name": "Vanne de sectionnement � 20 mm",
    "category": "autre",
    "specification": "� 20 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.01
  },
  {
    "id": "gm-158",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/93/9864",
    "name": "Vanne de sectionnement � 26 mm",
    "category": "autre",
    "specification": "� 26 mm",
    "active": true,
    "unit": "p",
    "base_price": 3.94
  },
  {
    "id": "gm-159",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/44/7431",
    "name": "Vanne de sectionnement � 32 mm",
    "category": "autre",
    "specification": "� 32 mm",
    "active": true,
    "unit": "p",
    "base_price": 8.09
  },
  {
    "id": "gm-160",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/96/2650",
    "name": "Vanne de sectionnement � 40 mm",
    "category": "autre",
    "specification": "� 40 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.37
  },
  {
    "id": "gm-161",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/50/4235",
    "name": "Vanne de sectionnement � 50 mm",
    "category": "autre",
    "specification": "� 50 mm",
    "active": true,
    "unit": "p",
    "base_price": 13.24
  },
  {
    "id": "gm-162",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/94/4703",
    "name": "Vanne de sectionnement � 63 mm",
    "category": "autre",
    "specification": "� 63 mm",
    "active": true,
    "unit": "p",
    "base_price": 16.53
  },
  {
    "id": "gm-163",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/31/5923",
    "name": "Isolation tubulaire mousse PE � 16 mm",
    "category": "autre",
    "specification": "� 16 mm",
    "active": true,
    "unit": "m",
    "base_price": 4.17
  },
  {
    "id": "gm-164",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/50/9456",
    "name": "Isolation tubulaire mousse PE � 20 mm",
    "category": "autre",
    "specification": "� 20 mm",
    "active": true,
    "unit": "m",
    "base_price": 9.45
  },
  {
    "id": "gm-165",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/11/2876",
    "name": "Isolation tubulaire mousse PE � 26 mm",
    "category": "autre",
    "specification": "� 26 mm",
    "active": true,
    "unit": "m",
    "base_price": 13.17
  },
  {
    "id": "gm-166",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/95/4931",
    "name": "Isolation tubulaire mousse PE � 32 mm",
    "category": "autre",
    "specification": "� 32 mm",
    "active": true,
    "unit": "m",
    "base_price": 14.48
  },
  {
    "id": "gm-167",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/11/6086",
    "name": "Isolation tubulaire mousse PE � 40 mm",
    "category": "autre",
    "specification": "� 40 mm",
    "active": true,
    "unit": "m",
    "base_price": 9.31
  },
  {
    "id": "gm-168",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/17/9175",
    "name": "Isolation tubulaire mousse PE � 50 mm",
    "category": "autre",
    "specification": "� 50 mm",
    "active": true,
    "unit": "m",
    "base_price": 10.77
  },
  {
    "id": "gm-169",
    "supplier": { "code": "GM", "name": "Getaz Miauton" },
    "reference": "GM/64/9022",
    "name": "Isolation tubulaire mousse PE � 63 mm",
    "category": "autre",
    "specification": "� 63 mm",
    "active": true,
    "unit": "m",
    "base_price": 13.78
  }
];
